### ISSUE TITLE
Gagal Menyinkronkan/Terhubung ke Beberapa Aplikasi

### ISSUE THREAD

**Issue by Wahyu4567** [bebasid/bebasdns#1]
Ketika bebasdns diaktifkan melalui DoT di Pengaturan Bawaan Android atau DoH menggunakan aplikasi pihak ketiga (seperti "Nebulo"). Aplikasi berikut menjadi gagal untuk menyinkronkan pembaruan/login ke server.

1. Microsoft Office (com.microsoft.office.officehubrow) - Gagal menyinkron ke OneDrive
2. YouTube (com.google.android.youtube) - Gagal menyinkron Histori Pemutaran
3̶.̶ ̶L̶a̶n̶o̶t̶a̶ ̶(̶c̶o̶m̶.̶N̶o̶x̶y̶g̶a̶m̶e̶s̶.̶L̶a̶n̶o̶t̶a̶)̶ ̶-̶ ̶G̶a̶g̶a̶l̶ ̶t̶e̶r̶h̶u̶b̶u̶n̶g̶ ̶k̶e̶ ̶s̶e̶r̶v̶e̶r̶/̶G̶a̶g̶a̶l̶ ̶l̶o̶g̶i̶n̶ ̶k̶a̶r̶e̶n̶a̶ ̶j̶a̶r̶i̶n̶g̶a̶n̶.̶   fixed

Penggunaan DNS pada browser (seperti Google Chrome) mungkin tidak berpengaruh terhadap masalah ini.

![Screenshot_2021-01-04-18-34-27-56_4ef330a40b3c1330285ee3a12af810fd](https://user-images.githubusercontent.com/76676441/103531247-86a8ea80-4ebb-11eb-805b-067ac00bfbdf.jpg)
![Screenshot_2021-01-04-18-29-33-24_4a24d271e133915ae237d4bec6ffe368](https://user-images.githubusercontent.com/76676441/103531079-36318d00-4ebb-11eb-969c-c98f1193e288.jpg)
![Screenshot_2021-01-04-18-29-28-46_7c6675ada7b05a8d2d5c5ffa2a487337](https://user-images.githubusercontent.com/76676441/103531087-3893e700-4ebb-11eb-8230-58e95d198081.jpg)
![Screenshot_2021-01-04-18-31-44-26](https://user-images.githubusercontent.com/76676441/103531091-39c51400-4ebb-11eb-84de-70091ffd7128.jpg)
![IMG_20210104_183134](https://user-images.githubusercontent.com/76676441/103531094-3a5daa80-4ebb-11eb-86a2-4a09d8aa5c2e.jpg)

**Comment by gvoze32** [comment]
Ditambahkan lanota kedalam whitelist

![image](https://user-images.githubusercontent.com/28755051/103557865-65112880-4ee6-11eb-9770-fad726168d40.png)

Untuk masalah youtube dan office dicek dari sini masih bisa, mungkin kamu bisa melakukan query ulang dan nanti akan dicek blocklist mana yang melakukan pemblokiran

**Comment by Wahyu4567** [comment]
Lanota dah fix dan bisa login. Namun untuk Youtube dan Office, gw bisa kirim logcat-nya disini

MS Office : https://pastebin.com/ZYa2HeG4
Youtube :  https://pastebin.com/aBRJ4sYu (yg ini gw kurang tau masalahnya dimana)

**Comment by gvoze32** [comment]
Ditambahkan login.live.com ke dalam rule
![gambar](https://user-images.githubusercontent.com/28755051/103604130-cc5cc600-4f42-11eb-8971-d58f36b3040e.png)

Bisa mengubah link pastebin youtube ke public agar bisa dicek?

**Comment by Wahyu4567** [comment]
Udah saya edit ke pubik. Coba buka lagi di atas

**Comment by gvoze32** [comment]
Masih belum bisa dibuka

**Comment by Wahyu4567** [comment]
Jika dibuka di hp, ya memang lag sampai force close karena teksnya kebanyakan. Di saya yang uploadnya make pc fine-fine aja.
Oh iya, link mirror jika masih ga bisa di buka : https://bit.ly/3dF1Fq5

**Comment by gvoze32** [comment]
Ditambahkan beberapa rule ke list, harusnya udah bisa semuanya, bisa bantu pengecekan?
![image](https://user-images.githubusercontent.com/28755051/103625745-fecfe880-4f6d-11eb-8cb4-d14037fb72db.png)

**Comment by Wahyu4567** [comment]
fixed. Semuanya sudah berjalan normal

**Comment by Wahyu4567** [comment]
Issue ini dibuka kembali untuk dns doh.kutu.my.id (Custom Filtering Rule tidak aktif???)

**Comment by gvoze32** [comment]
> 
> 
> Issue ini dibuka kembali untuk dns doh.kutu.my.id (Custom Filtering Rule tidak aktif???)

aktif, masuk ke whitelist
