### ISSUE TITLE
latency terlalu tinggi

### ISSUE THREAD

**Issue by 3xploiton3** [bebasid/bebasdns#11]
![image](https://user-images.githubusercontent.com/19517680/187878510-06964d2c-8d48-4c45-b804-4350087cf9fe.png)

latency terlalu tinggi, apakah bebasdns memakai server dalam negeri?

**Comment by nxzlem** [comment]
Sebisa nya kalo pemilik nya bisa ganti VPS hosting dengan alibaba ke indonesia untuk utamanya. Second, dia harus punya backup juga untuk vps alibaba di singapore nya

**Comment by SlashyID** [comment]
Server bebasdns sekarang di hosting di Malaysia jadinya latency nya tinggi 

Untuk saat ini, kita lagi proses agar punya server backup lokal di Indonesia

**Comment by SlashyID** [comment]
Selamat malam

Server BebasID di Indonesia sudah ada di Indonesia ya

Silahkan ping lagi 

`ping 147.139.211.126`
![image](https://github.com/bebasid/bebasdns/assets/115700386/ac216d8a-a682-4621-ac03-1fa4484d85ec)

**Comment by 3xploiton3** [comment]
> Selamat malam
> 
> Server BebasID di Indonesia sudah ada di Indonesia ya
> 
> Silahkan ping lagi
> 
> `ping 147.139.211.126` ![image](https://user-images.githubusercontent.com/115700386/238146526-ac216d8a-a682-4621-ac03-1fa4484d85ec.png)

![image](https://github.com/bebasid/bebasdns/assets/19517680/76b7292f-6017-4edc-bf54-6eacf1df5837)

tergolong masih tinggi, saya pakai plat merah lokasi jateng

**Comment by SlashyID** [comment]
@3xploiton3 

Boleh minta hasil tracert nya ke `147.139.211.126` ?

**Comment by 3xploiton3** [comment]
> 

![image](https://github.com/bebasid/bebasdns/assets/19517680/d2920329-67b9-4b0a-bd83-04598e309fea)

**Comment by nxzlem** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/19517680/238171325-d2920329-67b9-4b0a-bd83-04598e309fea.png)

boleh pengen tahu, ini ISP apa? Kok bisa roting nya buluk

**Comment by SlashyID** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/19517680/238171325-d2920329-67b9-4b0a-bd83-04598e309fea.png)

Dari hasil tracertnya, kemungkinan ISP nya gak stabil jaringannya buat routing ke server kami 🙏 

![image](https://github.com/bebasid/bebasdns/assets/115700386/6b4a2d30-bd1e-430b-9155-f956a49d8835)
Dari hop 5 sampai tujuan ping nya naik turun

Coba ping yg IPv6 bisa gak? Kan Indihome support IPv6

**Comment by 3xploiton3** [comment]
![image](https://github.com/bebasid/bebasdns/assets/19517680/2e708383-b476-4d87-9e0a-5b586322a3e6)

**Comment by SlashyID** [comment]
> ![image](https://user-images.githubusercontent.com/19517680/238172656-2e708383-b476-4d87-9e0a-5b586322a3e6.png)

Udah dinyalain di router / komputer?

**Comment by nxzlem** [comment]
Silakan periksa IP dan ISP anda di https://browserleaks.com/ip/

**Comment by 3xploiton3** [comment]
kurang ngerti cara nyalakan ipv6, memang wifi.id bisa dinyalakan dari sisi client?

![image](https://github.com/bebasid/bebasdns/assets/19517680/54c2dfc1-49a2-4155-a958-ab0c64175ff4)

**Comment by SlashyID** [comment]
Wifi.ID kan public dipake banyak orang, Jadinya gak stabil ping nya kalau lagi banyak yang make karena kemungkinan router yg digunain Telkom gak ada fitur bandwidth managementnya

Untuk menjawab pertanyaan seputar IPv6, kayaknya gak bisa diaktifin kecuali kalau jadi admin deh soalnya itu dari sononya

Mohon maaf atas tidak kenyamanan anda 🙏

**Comment by 3xploiton3** [comment]
> 

saya rasa pernyataan ini kurang tepat, kita bandingkan dengan dns 1.1.1.1 atau 8.8.8.8
walaupun ada spike di pertengahan, nyatanya di akhir latency stabil

![image](https://github.com/bebasid/bebasdns/assets/19517680/4ab5f82f-2f86-4db2-943e-0c32063645af)

**Comment by SlashyID** [comment]
Coba `ping 223.5.5.5`

Soalnya dari jaringan selain Telkom normal semua pingnya gak 200-an

**Comment by 3xploiton3** [comment]
memang buluk ping ke dns alibaba, 
![image](https://github.com/bebasid/bebasdns/assets/19517680/7330f6f3-b93c-4aee-9392-be6a8e7b0987)

sudah saya laporkan ke indihome care

**Comment by 3xploiton3** [comment]
> 147.139.211.126

ping sudah bagus, nice work
![image](https://github.com/bebasid/bebasdns/assets/19517680/0577e78a-c03b-4c03-bbb2-88c426f2973f)

**Comment by 3xploiton3** [comment]
> Kalau ping Server DNS BebasID Indo gimana sekarang?

saya pindah indi sekarang latency tinggi, ping ke dns.bebasid.com

![image](https://github.com/bebasid/bebasdns/assets/19517680/00b31497-7742-4056-94e8-0297bb9fe223)

**Comment by nxzlem** [comment]
> > Kalau ping Server DNS BebasID Indo gimana sekarang?
> 
> saya pindah indi sekarang latency tinggi, ping ke dns.bebasid.com
> 
> ![image](https://github.com/bebasid/bebasdns/assets/19517680/00b31497-7742-4056-94e8-0297bb9fe223)
> 
Itu sudah normal

**Comment by 3xploiton3** [comment]
kemarin bisa dibawah 20ms,

**Comment by nxzlem** [comment]
> kemarin bisa dibawah 20ms, 

Kami habis ganti karena DNS recursive

**Comment by NolPixel** [comment]
Udh bagus sih (pake data). Thank you! Sy pindahan dri adguard, kadang bikin buffering. Ping diatas 50ms. Pakai bi*net aja ping 15ms. Tp klo pk bebasid, ping 3ms. 

![IMG_0080](https://github.com/bebasid/bebasdns/assets/41100835/009497e7-f3df-4629-be8e-a70fb8552ad5)

**Comment by ryukora** [comment]
> 

Mantap

**Comment by SlashyID** [comment]
> > Kalau ping Server DNS BebasID Indo gimana sekarang?
> 
> saya pindah indi sekarang latency tinggi, ping ke dns.bebasid.com
> 
> ![image](https://user-images.githubusercontent.com/19517680/248544907-00b31497-7742-4056-94e8-0297bb9fe223.png)

Untuk IPv4 nya gimana? 
`103.87.68.24`

IPv6 kita itu Tunnel dari Singapura soalnya jadinya untuk ping nya emang tinggi

Kecuali untuk IPv6 yang DNS Antivirus `2001:df1:7340:c::beba:51d`

**Comment by 3xploiton3** [comment]
> > > Kalau ping Server DNS BebasID Indo gimana sekarang?
> > 
> > 
> > saya pindah indi sekarang latency tinggi, ping ke dns.bebasid.com
> > ![image](https://user-images.githubusercontent.com/19517680/248544907-00b31497-7742-4056-94e8-0297bb9fe223.png)
> 
> Untuk IPv4 nya gimana? `103.87.68.24`
> 
> IPv6 kita itu Tunnel dari Singapura soalnya jadinya untuk ping nya emang tinggi untuk beberapa ISP yang gak peering langsung sama provider tunnel IPv6 kita disana
> 
> Kecuali untuk IPv6 yang DNS Antivirus `2001:df1:7340:c::beba:51d`

IPv4 = GOOD,
![image](https://github.com/bebasid/bebasdns/assets/19517680/b5ecbd89-3436-421a-a82f-fe045b0ecdd7)

**Comment by SlashyID** [comment]
Kemungkinan Telkom routing ke IPv6 kita ngaco itu.

Soalnya dari Biznet sama CBN itu normal2 aja

Mungkin bisa lapor ke Indihome Care atau gimana

**Comment by 3xploiton3** [comment]
![image](https://github.com/bebasid/bebasdns/assets/19517680/5664ed5e-c3d3-4647-9d18-0f65d3fd06d6)

gagal melakukan ping ke ipv6

**Comment by SlashyID** [comment]
Apakah IPv6 di sistem sudah aktif?

Coba ping 2001:4860:4860::8888

**Comment by 3xploiton3** [comment]
maaf saya lupa mematikan nordvpn
![image](https://github.com/bebasid/bebasdns/assets/19517680/40f2251e-a160-4f0c-83bf-5deca5935359)

ISP Indihome
![image](https://github.com/bebasid/bebasdns/assets/19517680/9df21eed-c8b8-47be-beaf-67eb2c615126)
