### ISSUE TITLE
Custom filtering

### ISSUE THREAD

**Issue by neneeen** [bebasid/bebasdns#12]
Since https://dns.bebasid.com/login.html shows AGH login page I'm assuming you're using AGH. The [custom client setting in AGH](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients#settings) makes it trivial to provide customized filtering, eg

`https://dns.bebasid.com/dns-query` works just like it's now

`https://dns.bebasid.com/dns-query/family` enable safe search and parental control service,

`https://dns.bebasid.com/dns-query/security` only uses browsing security service,

`https://dns.bebasid.com/dns-query/unfiltered` doesn't use any filter

I give DoH examples because setting up the domain for DoT & DoQ would require a wildcard cert and it's way more annoying to set up with LetsEncrypt than a regular domain.

Granted, this is a really small niche, but setting it up for DoH only requires a few clicks, with no extra overhead.

**Comment by SlashyID** [comment]
This is a good idea, thank you for your suggestion!

We have already added unfiltered and family variant to filter NSFW 
`https://dns.bebasid.com/dns-query/family`

and unfiltered variant
`https://dns.bebasid.com/dns-query/unfiltered`
