### ISSUE TITLE
Port 5353

### ISSUE THREAD

**Issue by WarnetDalnet** [bebasid/bebasdns#16]
Please open port 5353

**Comment by SlashyID** [comment]
### Sorry for the inconvenience,

Currently, plain DNS variant BebasDNS is only listening on **Port 53** aswell as **Port 1753**

**If your ISP is using transparent DNS, you can use port 1753 for plain DNS or DoH/DoT/DoQ**

[You can follow the tutorial here](https://github.com/bebasid/bebasdns/blob/main/tutoraltport.md)
