### ISSUE TITLE
blocking doesn't work in youtube.com

### ISSUE THREAD

**Issue by bonbonsiregar** [bebasid/bebasdns#2]
It doesn't block the ads in youtube homepage and also the built in ads when loading a video. Also there are cosmetic issues in ads on the sidebar when viewing a video.

**Comment by gvoze32** [comment]
currently, no ad blocker is technologically capable of blocking ads in the native YouTube App on mobile devices

**Comment by bonbonsiregar** [comment]
What about the Youtube in desktop using browser? my issue is happening in Youtube desktop.

I'm using brave browser with brave shield active, but I see that bebasdns has custom filtering and adblocking feature so I turned off brave shield but the ads are visible instead.

**Comment by gvoze32** [comment]
DNS blocking of YouTube ads no longer works, because ads are injected into the stream and appear to originate from YouTube. In other words, if you want to block YouTube ads, it means blocking YouTube itself as well.

Use browser addons such as uBlock Origin instead.
