### ISSUE TITLE
BebasDNS DoH is breaking imdb.com?

### ISSUE THREAD

**Issue by PapoyBanana** [bebasid/bebasdns#3]
This is what it looks like when opening imdb.com with BebasDNS DoH on Firefox. I think the filters are too potent.

![image](https://user-images.githubusercontent.com/13683419/117159617-a0ffc000-adea-11eb-85bf-bfd159621620.png)

**Comment by gvoze32** [comment]
Fixed, removed Tiarapp from the list

**Comment by PapoyBanana** [comment]
Tiarap is the culprit? The site opens just fine with Tiarap DoH though. Well, thanks anyway.
