### ISSUE TITLE
Misal DNS Untuk Family Diadakan tolong blok ini

### ISSUE THREAD

**Issue by pc-v2** [bebasid/bebasdns#30]
Silahkan isi berikut dan sertakan detail nya untuk mengalami perubahan tersebut.

tolong block doh/dot berikut agar tidak bisa dipakai saat menggunakan family (misal bebasdns digunakan diluar browser)
```
chromium.dns.nextdns.io
firefox.dns.nextdns.io
one.one.one.one
family.cloudflare-dns.com
security.cloudflare-dns.com
1dot1dot1dot1.cloudflare-dns.com
free.shecan.ir
dns.njal.la
doh.mullvad.net
dns.twnic.tw
dns1.nextdns.io
doh.360.cn
doh.pub
dns.quad9.net
dns.alidns.com
dns.adguard-dns.com
family.adguard-dns.com
unfiltered.adguard-dns.com
dns-unfiltered.adguard.com
doh.familyshield.opendns.com
doh.opendns.com
freedns.controld.com
doh.cleanbrowsing.org
cloudflare-dns.com
dns2.nextdns.io
dns.nextdns.io
chrome.cloudflare-dns.com
mozilla.cloudflare-dns.com
firefox.dns.nextdns.io
```
dengan blokir lists diatas, doh/dot tidak dapat digunakan saat di browser agar tidak di override

**Comment by icaksh** [comment]
Terima kasih atas sarannya dan memang untuk DNS Family memang sedang direncanakan untuk aktif akan tetapi dalam waktu yang tidak singkat seperti satu minggu atau dua minggu kedepan mengingat bahwa dari BebasDNS melakukan migrasi arsitektur DNS yang semula monolitik dijadikan microservices dan sayangnya salah satu dari tim kami yang menangani arsitektur ini mengalami _slow respon_ yang berkaitan dengan hal lain

**Comment by SlashyID** [comment]
Sepertinya ini ide yang bagus 🙏

Terimakasih atas idenya namun untuk saat ini, BebasDNS Family lagi dalam proses pembuatan ulang dikarenakan server kita sudah ganti yang lebih baru jadi silahkan tunggu dulu ya

**Comment by SlashyID** [comment]
Selamat Siang,

DNS Family sudah kami terapkan.
Tetapi untuk yg blokir DoH/DoT akan segera kami terapkan dikarenakan kami punya dua versi DNS Family
- Default 
- Strict

Yang Default gak blokir DoH/DoT sedangkan yang strict bakal ngeblock

**Comment by SlashyID** [comment]
Halo, terimakasih atas usulan anda

BebasDNS telah membuat versi Family Strict yang akan memblokir provider DoH dan VPN lain

**DoH:** `https://internetsehat.bebasid.com/dns-strict`

Untuk versi DoT, sedang dalam pengembangan jadi mohon kesabaran anda 🙏
