### ISSUE TITLE
lists bebasdns yang bisa dibaca dnscrypt-proxy

### ISSUE THREAD

**Issue by TheWeatherIsCool** [bebasid/bebasdns#31]
Untuk mempermudah pengguna dalam menambahkan bebasdns ke dnscrypt-proxy, dapat menggunakan list daripada menggunakan static. Dengan menggunakan list, jika ada perubahan pada ip addressnya bebasdns, pengguna tidak perlu menggantinya secara manual.

[Format config list](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Configuration-Sources#configuring-the-sources-to-use)
[Format lists](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Configuration-Sources#creating-your-own-source)
[contoh lists](https://github.com/DNSCrypt/dnscrypt-resolvers/tree/master/v3)

**Comment by SlashyID** [comment]
Ini ide yang bagus 🙏🙏

Silahkan ditunggu ya

**Comment by SlashyID** [comment]
https://github.com/DNSCrypt/dnscrypt-resolvers/pull/847

Silahkan tunggu ya

**Comment by SlashyID** [comment]
OK Sudah ditambahkan ya 

![image](https://github.com/bebasid/bebasdns/assets/115700386/2c6584d5-3eae-4699-86fb-3c518bd64c0a)
