### ISSUE TITLE
Tambahkan tutorial pengaplikasian DNS DOH Native windows 11

### ISSUE THREAD

**Issue by 3xploiton3** [bebasid/bebasdns#32]
referensi 

https://learn.microsoft.com/en-us/windows-server/networking/dns/doh-client-support#add-a-new-doh-server-to-the-list-of-known-servers

https://help.nextdns.io/t/60hj3yd/enable-doh-natively-on-windows-11

https://www.elevenforum.com/t/enable-dns-over-https-doh-in-windows-11.280/

**Comment by 3xploiton3** [comment]
jika perlu dibuatkan script one click install, untuk memudahkan user

contoh
https://github.com/helgeklein/Win-DNS-DoH-PoSh

**Comment by 3xploiton3** [comment]
ini tutorial dari saya yang ringkas

1. buka terminal/cmd/powershell
2. tempel kode `netsh dns add encryption 103.87.68.24 https://dns.bebasid.com/dns-query`
3. Buka Network and Internet Settings
4. Pilih Ethernet atau Wifi
5. Edit DNS setting
6. Save
![image](https://github.com/bebasid/bebasdns/assets/19517680/4c9ebbdb-e813-4d18-a6d7-a47397bde3e6)

**Comment by 3xploiton3** [comment]
bukti dns no leak (kebocoran) dari https://dnsleaktest.com/ 
pastikan pilih **extended test**

![image](https://github.com/bebasid/bebasdns/assets/19517680/06533700-da5f-465b-a8f1-bbe9ff68542d)

**Comment by SlashyID** [comment]
Baik nanti tim kita tambahkan 🙏

Terimakasih ya

**Comment by 3xploiton3** [comment]
Tambahan: untuk chrome ataupun browser berbasis chromium "perlu disable Async DNS resolver"

![image](https://github.com/bebasid/bebasdns/assets/19517680/f8b80a46-7f82-45a4-8905-8263143e425f)

**Comment by MilkFullCream** [comment]
> Tambahan: untuk chrome ataupun browser berbasis chromium "perlu disable Async DNS resolver"
> 
> ![image](https://user-images.githubusercontent.com/19517680/256259409-f8b80a46-7f82-45a4-8905-8263143e425f.png)

ga perlu disable ginian, browser bakal otomatis pake dns pertama (windows/isp) itu juga kalo ga di oprek, malah fitur ini di butuhkan buat aktifin ECH di Chromium (edge, brave, chrome, dll) dan kedua " Async DNS resolver " sudah di hapus di flagnya miscrosoft edge jadi harus oprek di policynya, ketiga bebasdns udah support ECH (wih keren nih) kalo matiin ini ECH ga bakal working

**Comment by 3xploiton3** [comment]
silahkan test yang pakai internet dari ISP yang menerapkan dns transparent, contoh (indi) 
karena di device saya tidak akan aktif menggunakan DOH bebasdns jika tidak di disabled fitur " **Async DNS resolver** "

**Comment by SlashyID** [comment]
Sudah ditambahkan ya 🙏

Terimakasih atas saran nya
