### ISSUE TITLE
[whitelist] dr-farfar.com

### ISSUE THREAD

**Issue by 3xploiton3** [bebasid/bebasdns#33]
**Deskripsi mengenai bug**
https://github.com/hagezi/dns-blocklists/issues/1336

**Screenshot**
![image](https://github.com/bebasid/bebasdns/assets/19517680/07acbff2-6ff6-494e-997d-d12d5b8d3dab)

**Comment by SlashyID** [comment]
Sudah kami whitelist ya silahkan clear cache browser anda dan cek ulang 🙏
