### ISSUE TITLE
soal http3

### ISSUE THREAD

**Issue by unknown4849** [bebasid/bebasdns#34]
ada kah rencana dalam waktu dekat bebasdns support http3 ?

**Comment by SlashyID** [comment]
Sayangnya server yang kami gunakan tidak mendukung http3 untuk saat ini.

Nanti kalau server kami mendukung, kami akan menambahkan dukungan untuk http/3

**Comment by DarkMProgrammer** [comment]
Selamat Malam,

Kami mohon maaf, software yang kami gunakan untuk saat ini belum mendukung http3, jadi kemungkinan http3 akan tersedia di masa depan saat software yang kami gunakan mendukung http3.

Untuk sementara, silahkan pake DNS over QUIC kami, Terima kasih
