### ISSUE TITLE
[BUG] bebasDNS down

### ISSUE THREAD

**Issue by 3xploiton3** [bebasid/bebasdns#37]
sekitar pukul 18:16-18.18 WIB apakah bebasdns down?
sempat tidak bisa ngakses domain, tapi ping ke ip lancar,

![image](https://github.com/bebasid/bebasdns/assets/19517680/f17edc1c-c45b-4064-8fef-f7e5e3d5008e)

**Comment by ryukora** [comment]
bebasdns sudah up lagi, silahkan restart dns nya anda
