### ISSUE TITLE
Status dns Down

### ISSUE THREAD

**Issue by GrennKren** [bebasid/bebasdns#4]
Apakah layanan dns ini memang sengaja dihentikan atau masih dalam proses maintenance ya

**Comment by benyaminl** [comment]
Seems money can't keep it up. ada yang local juga https://doh.linuxsec.org/adguard Server IIX proxy ke AdGuard, no log

Yang LN ada BlahDNS sama nextDNS

**Comment by gvoze32** [comment]
bebasdns maintenance dan masih proses buat up, estimasi besok jadi, sudah ada donatur vps

**Comment by benyaminl** [comment]
Untuk layanan ini port apa saja yang harus dibuka ya? Apakah hanya 443
saja? Thanks

**Comment by gvoze32** [comment]
Ada DoH yang beroperasi pada port 443 dan DoT beroperasi melalui port 853

**Comment by gvoze32** [comment]
Maintenance selesai dengan penambahan fitur DNS-over-QUIC

https://github.com/bebasid/bebasdns/commit/414a0e3236bcf6ecf7d639860594697fba2b3da1
