### ISSUE TITLE
[BUG] ojrq.net: whitelist

### ISSUE THREAD

**Issue by 3xploiton3** [bebasid/bebasdns#40]
https://www.ojrq.net/p/?return=https%3A%2F%2F1.envato.market%2Fc%2F1240788%2F480739%2F4415%3Fu%3Dhttp%3A%2F%2Fthemeforest.net%2Fuser%2FDankovThemes%26level%3D1&cid=4415&tpsync=yes&auth=55fffe3c8f085000

affiliate link: maybe

**Comment by SlashyID** [comment]
**Selamat malam,**

Terimakasih sudah membuat issue ini
Boleh kasih penjelasan apa dan kenapa situs orjq(dot)net harus diunblock?

Soalnya kita searching di Internet link nya, banyak muncul ginian:

![image](https://github.com/bebasid/bebasdns/assets/115700386/c34ac4da-2a13-4fe4-a79b-61fc65075fe3)

**Comment by 3xploiton3** [comment]
itu hanya link affiliate, tidak berbahaya, dulu saya sudah klaim ke ke oisd.nl lalu mereka whitelist,
website2 besar menggunakannya, contoh email newsletter dari envato,

**Comment by ryukora** [comment]
> itu hanya link affiliate, tidak berbahaya, dulu saya sudah klaim ke ke oisd.nl lalu mereka whitelist, website2 besar menggunakannya, contoh email newsletter dari envato,

bisa kah anda memberikan source/sumber link nya yang di whitelist kan?

**Comment by 3xploiton3** [comment]
https://github.com/bebasid/bebasdns/issues/40#issue-1829807616

itu sudah saya sampaikan diawal, nanti bila ada lagi link lain yang bermasalah saya sampaikan lagi disini, tolong issue tetap dibuka,

**Comment by ryukora** [comment]
> [#40 (comment)](https://github.com/bebasid/bebasdns/issues/40#issue-1829807616)
> 
> itu sudah saya sampaikan diawal, nanti bila ada lagi link lain yang bermasalah saya sampaikan lagi disini, tolong issue tetap dibuka,

Diskusi di discord aja, kita bisa membantu secepatnya 🙏

**Comment by SlashyID** [comment]
Sebentar ya kita whitelist dari sistem

**Comment by SlashyID** [comment]
![image](https://github.com/bebasid/bebasdns/assets/115700386/a270c299-1d7f-4b79-b0f6-e68df97bbc7b)

Sudah kami whitelist, silahkan hapus cache anda dan coba lagi 🙏
