### ISSUE TITLE
[BUG] subscene.com

### ISSUE THREAD

**Issue by 3xploiton3** [bebasid/bebasdns#41]
![image](https://github.com/bebasid/bebasdns/assets/19517680/159b6aae-1918-4db1-b734-53e7a7dd7d0b)

DNS DOH Native Windows 11 22H2

**Comment by ryukora** [comment]
ISP anda memakai DPI

**Comment by 3xploiton3** [comment]
domain sudah bisa dibuka kembali

**Comment by SlashyID** [comment]
**Selamat malam**

Jika anda mendapat error tersebut, itu merupakan tanda provider internet anda menerapkan DPI (Deep Packet Inspection) yang membuat metode bypass DNS dan Host tidak akan berfungsi dikarenakan Firewall provider aktif untuk membaca situs yang kita kunjungi.

**Jika muncul error tersebut dimasa depan, silahkan gunakan tool untuk membypass DPI seperti:**
- [GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI/releases)
- [PowerTunnel](https://github.com/krlvm/PowerTunnel)
- [GreenTunnel](https://github.com/SadeghHayeri/GreenTunnel)

Tetapi, jika anda ingin membypass DPI di level router, silahkan ikuti cara ini:
- [OpenWRT](https://github.com/bebasid/bebasit/blob/master/docs/openwrt-tutorial.md)
- [MikroTik RouterOS](https://github.com/bebasid/bebasit/blob/master/docs/mikrotik-tutorial.md)

Kami mohon maaf atas tidak kenyamanan anda. Jika masih ada pertanyaan, silahkan jawab komentar ini atau membuka issuenya lagi 🙏

**Terimakasih,
Slashy**

**Comment by 3xploiton3** [comment]
> **Selamat malam**
> 
> Jika anda mendapat error tersebut, itu merupakan tanda provider internet anda menerapkan DPI (Deep Packet Inspection) yang membuat metode bypass DNS dan Host tidak akan berfungsi dikarenakan Firewall provider selalu aktif untuk membaca situs yang kita kunjungi.
> 
> **Jika muncul error tersebut dimasa depan, silahkan gunakan tool untuk membypass DPI seperti:**
> 
> * [GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI/releases) _(Kecuali user Telkomsel, XL, dan Iconnet)_
> * [PowerTunnel](https://github.com/krlvm/PowerTunnel)
> * [GreenTunnel](https://github.com/SadeghHayeri/GreenTunnel)
> 
> Tetapi, jika anda ingin membypass DPI di level router, silahkan ikuti cara ini:
> 
> * [OpenWRT](https://github.com/bebasid/bebasit/blob/master/docs/openwrt-tutorial.md)
> * [MikroTik RouterOS](https://github.com/bebasid/bebasit/blob/master/docs/mikrotik-tutorial.md) (Kecuali user Telkomsel, XL, dan Iconnet)
> 
> Kami mohon maaf atas tidak kenyamanan anda. Jika masih ada pertanyaan, silahkan jawab komentar ini atau membuka issuenya lagi.
> 
> **Terimakasih, Slashy**

bukannya DOH tidak bisa di bypass oleh ISP? karena sudah terenkripsi,
saya belum pernah menemukan error seperti ini di nextdns dengan menggunakan metode sama DNS DOH Native Windows 11

**Comment by ryukora** [comment]
> > **Selamat malam**
> > Jika anda mendapat error tersebut, itu merupakan tanda provider internet anda menerapkan DPI (Deep Packet Inspection) yang membuat metode bypass DNS dan Host tidak akan berfungsi dikarenakan Firewall provider selalu aktif untuk membaca situs yang kita kunjungi.
> > **Jika muncul error tersebut dimasa depan, silahkan gunakan tool untuk membypass DPI seperti:**
> > 
> > * [GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI/releases) _(Kecuali user Telkomsel, XL, dan Iconnet)_
> > * [PowerTunnel](https://github.com/krlvm/PowerTunnel)
> > * [GreenTunnel](https://github.com/SadeghHayeri/GreenTunnel)
> > 
> > Tetapi, jika anda ingin membypass DPI di level router, silahkan ikuti cara ini:
> > 
> > * [OpenWRT](https://github.com/bebasid/bebasit/blob/master/docs/openwrt-tutorial.md)
> > * [MikroTik RouterOS](https://github.com/bebasid/bebasit/blob/master/docs/mikrotik-tutorial.md) (Kecuali user Telkomsel, XL, dan Iconnet)
> > 
> > Kami mohon maaf atas tidak kenyamanan anda. Jika masih ada pertanyaan, silahkan jawab komentar ini atau membuka issuenya lagi.
> > **Terimakasih, Slashy**
> 
> bukannya DOH tidak bisa di bypass oleh ISP? karena sudah terenkripsi, saya belum pernah menemukan error seperti ini di nextdns dengan menggunakan metode sama DNS DOH Native Windows 11

doh bisa di bypass kecuali isp nya menggunakan dpi, jika misalnya isp anda mendukung ipv6 dan belum kena dnsn, anda bisa menggunakan itu.

**Comment by SlashyID** [comment]
> > **Selamat malam**
> > Jika anda mendapat error tersebut, itu merupakan tanda provider internet anda menerapkan DPI (Deep Packet Inspection) yang membuat metode bypass DNS dan Host tidak akan berfungsi dikarenakan Firewall provider selalu aktif untuk membaca situs yang kita kunjungi.
> > **Jika muncul error tersebut dimasa depan, silahkan gunakan tool untuk membypass DPI seperti:**
> > 
> > * [GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI/releases) _(Kecuali user Telkomsel, XL, dan Iconnet)_
> > * [PowerTunnel](https://github.com/krlvm/PowerTunnel)
> > * [GreenTunnel](https://github.com/SadeghHayeri/GreenTunnel)
> > 
> > Tetapi, jika anda ingin membypass DPI di level router, silahkan ikuti cara ini:
> > 
> > * [OpenWRT](https://github.com/bebasid/bebasit/blob/master/docs/openwrt-tutorial.md)
> > * [MikroTik RouterOS](https://github.com/bebasid/bebasit/blob/master/docs/mikrotik-tutorial.md) (Kecuali user Telkomsel, XL, dan Iconnet)
> > 
> > Kami mohon maaf atas tidak kenyamanan anda. Jika masih ada pertanyaan, silahkan jawab komentar ini atau membuka issuenya lagi.
> > **Terimakasih, Slashy**
> 
> bukannya DOH tidak bisa di bypass oleh ISP? karena sudah terenkripsi, saya belum pernah menemukan error seperti ini di nextdns dengan menggunakan metode sama DNS DOH Native Windows 11

DoH memang bisa bypass kalau ISP nya tidak aktif untuk membaca domain yang kita kunjungi.

Sebenernya ada 2 hal lagi yang ISP bisa baca

SNI header sama Host header 

DPI Kominfo targetin kedua itu
