### ISSUE TITLE
[REQ] Request Versi DNS Yang unfiltered

### ISSUE THREAD

**Issue by RelvinArsenio** [bebasid/bebasdns#42]
Kalian ada rencana buat versi DNS yang unfiltered tidak?
yang dimana tidak memfilter apapun baik itu ads maupun tracking.

**Comment by SlashyID** [comment]
Iya ini termasuk perencanaan kita

Tapi yang unfiltered cuman support DoH/DoT doang ya soalnya kita cuman punya 3 IP Publik

**Comment by RelvinArsenio** [comment]
Nah gpp yang penting ada versi unfiltered.
Soalnya kurang percaya aku dengan filternya.

**Comment by ryukora** [comment]
> Nah gpp yang penting ada versi unfiltered. Soalnya kurang percaya aku dengan filternya.

Buat sementara, pake yang dns antivirus saja

**Comment by SlashyID** [comment]
Selamat Pagi,

DNS Unfiltered sudah tersedia ya 

[Silahkan pergi ke halaman ini untuk menggunakan nya](https://github.com/bebasid/bebasdns/blob/main/README.md#dns-unfiltered)

Jika anda ada masalah dengan DNS Unfiltered kami, jangan ragu-ragu untuk membuka issue baru

Salam,
Team BebasID
