### ISSUE TITLE
[REQ] Ubah Penyaring (Ad-Blocker & Anti-Tracking)

### ISSUE THREAD

**Issue by RelvinArsenio** [bebasid/bebasdns#43]
Menurut pendapatku, [HaGeZi's Light DNS Blocklist](https://github.com/hagezi/dns-blocklists/#light) itu lebih bagus dari pada yang di bawah ini:

- [oisd Blocklist Big](https://big.oisd.nl/unbound)
- [Windows Spy Blocker](https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/firewall/update.txt)
- [Online Malicious URL Blocklist](https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-unbound.conf)
- [NoTracking](https://raw.githubusercontent.com/notracking/hosts-blocklists/master/unbound/unbound.blacklist.conf)

Blocklists, [HaGeZi's Light DNS Blocklist](https://github.com/hagezi/dns-blocklists/#light) udah termasuk semua yang ada di daftar di atas, plus tambahan lainnya. Jadi saran aku, tim di Bebasid bisa pertimbangkan buat ganti semua yang lama dengan [HaGeZi's Light DNS Blocklist](https://github.com/hagezi/dns-blocklists/#light). Bahkan beberapa situs yang tadinya ada di daftar kustom Bebasid juga udah masuk ke [HaGeZi's Light DNS Blocklist](https://github.com/hagezi/dns-blocklists/#light).

Aku udah test di web [d3ward.github.io](https://d3ward.github.io/toolz/adblock.html) dan tingkat pemblokirannya sampe 99% dan hampir gak ada yang terlewat. Jadi menurutku, ini pilihan yang bagus.

Tapi ya, kalo masih ada yang kurang, ada opsi lain juga, bisa cek [HaGeZi's Normal DNS Blocklist](https://github.com/hagezi/dns-blocklists/#multi-normal---all-round-protection-) yang melindungi lebih luas lagi.

Apa lagi itu khusus untuk DNS Blocklists.

**Comment by SlashyID** [comment]
Dulu kita pernah pake Hagezi tapi terlalu sensitif sampai ada user yang complain link beberapa e commerce jadi rusak

**Comment by RelvinArsenio** [comment]
aku sangat mengharapkan itu.
atau buat saja versi doh/dot dengan list itu.
Khusus untuk yang light.
dengan nama noads.bebasid.com.

**Comment by ryukora** [comment]
> Saya pakai gk pernah bermasalah, yang light tapi jangan yang pro / pro++ kalau yang pro / pro++ banyak situs rusak.

Kami make filter yang hagezi multi normal, bukan pro / pro++

**Comment by RelvinArsenio** [comment]
> 

coba yang light.
aku pake nextdns pakai filter itu aman.
mbangking aman sosmed aman, e-commerce aman.

**Comment by SlashyID** [comment]
OK, kita akan coba ya 🙏

**Comment by MilkFullCream** [comment]
malah menurutku hagezi normal ke atas ga ada kendala sama sekali dan hagezi pun cukup aktif buat hapus false positif.

saya sendiri pake hagezi ultimate di nextdns dan semua app lancar tanpa kendala.

**Comment by RelvinArsenio** [comment]
> malah menurutku hagezi normal ke atas ga ada kendala sama sekali dan hagezi pun cukup aktif buat hapus false positif.
> 
> saya sendiri pake hagezi ultimate di nextdns dan semua app lancar tanpa kendala.

Nah makanya, saya bingung kok ada yang komplain masalah e-commerce gk jalan

Jangankan yang ultimate, yang Light aja bagus banget.

Dari pada pakai banyak seperti itu.
Mendingan satu aja tapi mencakup semuanya

**Comment by SlashyID** [comment]
Sudah kami ganti ya silahkan cek kembali dan hapus cache anda 🙏 

Terimakasih atas usulan nya
