### ISSUE TITLE
[BUG] accesstrade.co.id: whitelist

### ISSUE THREAD

**Issue by 3xploiton3** [bebasid/bebasdns#44]
https://accesstrade.co.id/

regular website

![image](https://github.com/bebasid/bebasdns/assets/19517680/eed368cf-e3fe-4bd2-a2c2-f525e73cff5a)

**Comment by MilkFullCream** [comment]
https://github.com/hagezi/dns-blocklists/issues/1406

udah ku bantu lapor ke Hagezi, kalo ada yang mau nambah info silahkan, wajib pake bahasa inggris ya 😅

**Comment by SlashyID** [comment]
Sebentar kita whitelist dulu ya.

Filter nya diblock sama Hagezi 🙏

**Comment by SlashyID** [comment]
![image](https://github.com/bebasid/bebasdns/assets/115700386/915e3ce5-2256-44cf-8816-ef64ebe4820d)

Sudah kami whitelist ya 🙏 

Silahkan hapus cache anda dan coba lagi
