### ISSUE TITLE
[Question] DNS Family

### ISSUE THREAD

**Issue by RelvinArsenio** [bebasid/bebasdns#46]
Apakah ide yang bagus, kalau DNS versi Family bikin situs 18+ di-redirect ke [internetpositif.id](https://internetpositif.id/) dan semua yang difilter sama DNS versi Family juga ke situ, ketimbang cuma dikasih IP 0.0.0.0?

**Comment by SlashyID** [comment]
Selamat Pagi, 

Kita sudah ada Halaman _Internet Positif_ sendiri.

![image](https://github.com/bebasid/bebasdns/assets/115700386/08305ebc-fa4f-4871-a04b-64b1a0eff905)

Secara default, situs yang diblok karena alasan 18+ akan dibelokan kesitu kecuali situs tersebut juga dikategorikan sebagai malware/phishing
