### ISSUE TITLE
[REQ/FIX] Block other BebasID DNS variant

### ISSUE THREAD

**Issue by pc-v2** [bebasid/bebasdns#48]
block varian lain dari bebasdns saat memakai internet sehat strict agar tidak terjadi kebobolan

**Comment by SlashyID** [comment]
Hampir semua varian sudah diblok kecuali yg Family

Kalau boleh tau, yang mana aja yang belum diblok ya?

**Comment by pc-v2** [comment]
masih bisa dibobol di chrome
semua varian dari dns.bebasid.com (unfiltered maupun filtered)
DoH varian antivirus aman

**Comment by pc-v2** [comment]
![image](https://github.com/bebasid/bebasdns/assets/58063311/25f8c832-7558-4cc7-8e88-154b3864371e)

**Comment by pc-v2** [comment]
masalah yogadns sepertinya

**Comment by SlashyID** [comment]
Sebentar kita cek dulu ya

**Comment by SlashyID** [comment]
Silahkan coba lagi

**Comment by pc-v2** [comment]
dns.bebasid.com
![image](https://github.com/bebasid/bebasdns/assets/58063311/2fc50036-641d-4581-b88b-79425e15e5c6)
![image](https://github.com/bebasid/bebasdns/assets/58063311/e44ea98f-b040-4cbc-ae5a-65e73d510a09)
google dns
![image](https://github.com/bebasid/bebasdns/assets/58063311/472414e0-39fd-4aba-869c-6f3186d86265)
cloudflare gak tembus

**Comment by pc-v2** [comment]
hahahahah agak lucu sih, setidaknya tidak seperti dns nasional bebasid ini

**Comment by pc-v2** [comment]
UPDATE
pake dnscrypt bisa keblokir
