### ISSUE TITLE
[REQ/FIX] Kesalahan di list dnscrypt-proxy project

### ISSUE THREAD

**Issue by HDark15** [bebasid/bebasdns#49]
Saya memakai app YogaDNS dan saat tau bebasdns akhirnya ada di list dnscrypt-proxy, saya check yg ada teks unfiltered cuma yg DOH.

![asCapture](https://github.com/bebasid/bebasdns/assets/34807171/74e73df0-d124-4a21-aa86-7b593921783e)

Saya bingung yg ada nama dnscrypt cuma satu padahal sama2 dnscrypt, saya check ke website dnscrypt-proxy

![asddasd](https://github.com/bebasid/bebasdns/assets/34807171/72937c7c-7516-4d8a-a155-83ac77b09244)

bebasdns-dnscrypt itu yg unfiltered tapi pas check ip itu untuk yg Peladen Utama

![qwCapture](https://github.com/bebasid/bebasdns/assets/34807171/2d1aaf11-326e-49af-9317-287d037f9b21)

Saya belom check yg lain karena hanya ingin memakain dnscrypt yg unfiltered dan mengapa bisa tidak di masukan ke list dnscrypt-proxy dari awal?

**Comment by SlashyID** [comment]
IP yang 34.101.185.130 juga berfungsi sebagai loadbalancer juga kecuali yang plain. yang plain murni untuk yang default

**Comment by DarkMProgrammer** [comment]
https://github.com/DNSCrypt/dnscrypt-resolvers/pull/854#event-10927756261

OK Sudah kami update ya 🙏
