### ISSUE TITLE
[REQ/FIX] Block animetime.pw 

### ISSUE THREAD

**Issue by pc-v2** [bebasid/bebasdns#50]
berisi 18+

**Comment by DarkMProgrammer** [comment]
Sudah kami cek dan lakukan pemutusan akses. 

Silahkan clear cache DNS anda dan coba

![image](https://github.com/bebasid/bebasdns/assets/115700386/f93f2ca9-c076-458d-8aeb-5adf3b4e8df5)

Terimakasih ya 🙏
