### ISSUE TITLE
[BUG] DoH Hagezi, OISD dan Devdan timeout

### ISSUE THREAD

**Issue by martheen** [bebasid/bebasdns#51]
**Deskripsi mengenai bug**
Waktu pakai varian Hagezi, OISD dan Devdan timeout

**Device**
 - OS: Windows 11 & Ubuntu 22.04
 - Sudah dicoba di Chrome, Firefox, dan CLI tools dnslookup (GET) dan bulldohzer (POST)

**Comment by DarkMProgrammer** [comment]
Sebentar kita cek 🙏

**Comment by DarkMProgrammer** [comment]
Apakah masih mati?

**Comment by martheen** [comment]
Masih mati ketiganya malah merembet `https://internetsehat.bebasid.com/dns-strict` ikut mati juga. FYI gua ngeceknya DoH, kalo DoT barusan ngecek yang devdan nyala, entah yang lain.

**Comment by martheen** [comment]
Ah, pas dicoba di Firefox & curl (keduanya pake POST), jalan. Yang trouble di bulldohzer (ini pake POST juga padahal), dnslookup (pake GET), upstream AdGuard Home (pake GET), seingat gua sih produk AdGuard manggil GET semua.

**Comment by DarkMProgrammer** [comment]
Kalau selain bulldohzer jalan kan? Soalnya untuk varian DNS selain default, family (non strict), sama security, upstream DoH nya pake AdGuard Home.

Nanti kita cek lagi deh. Boleh screenshot errornya kaya gimana?

**Comment by martheen** [comment]
![image](https://github.com/bebasid/bebasdns/assets/7911769/d7a050c7-688c-4849-80de-b91ad94ef781)
Ini pas nyoba nambah sebagai upstream di AdGuardHome,

![image](https://github.com/bebasid/bebasdns/assets/7911769/f6d8cf7d-9a23-4b78-8efe-51ee7cfab638)
Ini pas manggil dari dnslookup

**Comment by DarkMProgrammer** [comment]
Selamat Pagi,

Untuk DNS Unfiltered sama Internet Sehat (Family) strict, harusnya sudah bisa sekarang
![image](https://github.com/bebasid/bebasdns/assets/115700386/eb24babb-1392-4aed-9ef9-c73a87406978)

Sekarang kami lagi dalam proses untuk memperbaiki DNS Custom Filtering

**Comment by martheen** [comment]
Sip, disini tes dengan tambah upstream di AGH, dnslookup maupun bulldohzer udah bisa utk internet sehat

**Comment by DarkMProgrammer** [comment]
![image](https://github.com/bebasid/bebasdns/assets/115700386/e0d45d8b-26cf-4cfb-b7b8-df58bc25cd0b)

Untuk Custom Filtering, apakah sudah bisa? Di Chrome sisi kita udah berfungsi

**Comment by martheen** [comment]
![image](https://github.com/bebasid/bebasdns/assets/7911769/cd43fd31-e852-4449-b107-4e3a004e29cc)
Masih belum bisa di AGH 

dnslookup juga gagal 
![image](https://github.com/bebasid/bebasdns/assets/7911769/f7c87084-82ea-41aa-84e9-1e99792c52cf)

bulldohzer (POST) juga gagal
![image](https://github.com/bebasid/bebasdns/assets/7911769/31d1c4e9-2da7-40fb-9c2e-c019f133ed15)

**Comment by DarkMProgrammer** [comment]
OK sebentar ya kita maintenance sementara dulu DNS Custom Filtering nya 🙏 

Mohon maaf atas tidak kenyamanan anda

**Comment by DarkMProgrammer** [comment]
Boleh tau anda pakai provider apa?

**Comment by DarkMProgrammer** [comment]
Kalau misalkan pake Telkomsel, Indihome dan sebagainya, coba `dns.bebasid.com` nya diganti jadi `fudgekomsel.dns.bebasid.com`

**Comment by martheen** [comment]
Di rumah Telkom, VPS di Oracle Jepang. Ini mestinya nggak terkait ISP karena toh saat pakai Warp pun juga tetap bermasalah.

**Comment by DarkMProgrammer** [comment]
Ohhh ok kalau gitu sebentar 🙏

**Comment by DarkMProgrammer** [comment]
![image](https://github.com/bebasid/bebasdns/assets/115700386/4542aa58-93e7-4d04-9f14-f10ba9d1eed9)

Untuk OISD dan Hagezi, apakah sudah bisa?

**Comment by martheen** [comment]
Hmm, kalau POST dengan bulldohzer udah normal ketiganya
![image](https://github.com/bebasid/bebasdns/assets/7911769/f4b82851-1046-493d-b58a-f2278c42b1d2)

tapi  untuk GET di AdGuard Home devdan doang yang belum jalan 
![image](https://github.com/bebasid/bebasdns/assets/7911769/99d7716e-84d7-4d1c-ac44-c951bdc5945c)

**Comment by martheen** [comment]
Ah sip dah jalan semua 
![image](https://github.com/bebasid/bebasdns/assets/7911769/529e0c27-ccde-4519-8b76-ee0ab5140409), thank you thank you
