### ISSUE TITLE
[REQ/FIX] blok situs 18+

### ISSUE THREAD

**Issue by kannnnna9** [bebasid/bebasdns#52]
Saya menggunakan browser berbeda dan keduanya tentu menggunakan bebasdns

Pada browser pertama saya masih dapat mengakses situs https://mangasusuku.xyz/ melalui domain https://mangasusu.cc

Sedangkan pada browser kedua tidak terbuka.

**Comment by kannnnna9** [comment]
> Saya menggunakan browser berbeda dan keduanya tentu menggunakan bebasdns
> 
> Pada browser pertama saya masih dapat mengakses situs https://mangasusuku.xyz/ melalui domain https://mangasusu.cc
> 
> Sedangkan pada browser kedua tidak terbuka.

Ternyata situs diatas masih bisa di buka di kedua browser saya, tolong tambahan blokir untuk family filter 🙏

**Comment by merdekaid** [comment]
Selamat Pagi, kita sudah add ya...
Terimakasih.

![image](https://github.com/bebasid/bebasdns/assets/115700386/b9360f93-7b73-4e3d-8853-dc47ee569069)
