### ISSUE TITLE
DoH & DoT Tidak Merespon

### ISSUE THREAD

**Issue by dammxs** [bebasid/bebasdns#6]
Halo, terimakasih untuk project bebas DNS anda!
Saya ingin melaporkan untuk DoH & DoT tidak mau terkoneksi di perangkat saya, Sony 1 ii(Android 11) & Mi 9T Pro(custom rom android 12). Sudah mencoba DoT di Laptop saya dan hasilnya sama, tidak dapat terhubung internet, untuk ISP yang saya gunakan yaitu 3(Three), by.U, Indihome.
Sekali lagi terimakasih untuk project bebas DNS anda yang sudah sangat membantu!

**Comment by gvoze32** [comment]
@dammxs Apakah sekarang sudah bisa? Untuk kasus tidak dapat terhubung biasanya disebabkan oleh adanya pembaruan filter daftar blokir dan daftar putih secara terjadwal, yang menyebabkan resource pada VPS terganggu, biasanya hanya berlangsung selama beberapa menit.

**Comment by gvoze32** [comment]
Setelah saya selidiki ulang ternyata masalah ada pada sertifikat ssl yang ada, terima kasih sudah melaporkan, sudah ditest dan harusnya sekarang sudah bisa.
