### ISSUE TITLE
DoH dan DoT tidak bisa bypass internet sehat di jaringan Telkomsel 

### ISSUE THREAD

**Issue by NiteFthr** [bebasid/bebasdns#8]

**Comment by mrsnax** [comment]
Benar sampai saat ini belum bisa di bypass

**Comment by SlashyID** [comment]
Halo, Telkomsel, XL, 3, dan provider seluler lain menggunakan DPI untuk memblokir website sehingga mengganti DNS itu tidak cukup.

Silahkan gunakan [PowerTunnel](https://github.com/krlvm/PowerTunnel-Android/releases) atau [GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI/releases) untuk membypass DPI
